[package]
name = "learning-webdev"
version = "0.1.0"
edition = "2021"

[dependencies]
const_format = "0.2.34"
lazy_static = "1.5.0"
soa_derive = "0.13.0"
strum = { version ="0.26.3", features = ["derive"] }
strum_macros = "0.26.4"

[dev-dependencies]
test-generator = "^0.3"
yaml-rust = "0.4.5"
